### ISSUE TITLE
Adding exercises with unit tests

### ISSUE THREAD

**Issue by tobiasgwaaler** [commercialhaskell/haskelldocumentation#15]
Hi,

A while ago I made some exercises for a series of workshops for teaching (elementary) Haskell. I would very much like to contribute them to this repo, if that's of interest to you? 

The exercises can be found here:
https://github.com/tobiasgwaaler/hands-on-haskell
(I would revise and improve them before contributing to `haskelldocumentation`)

**Comment by k-bx** [comment]
@tobiasgwaaler slightly off-topic: you recommend Haskell Platform, but it's known for quickly becoming old and has high possibility of introduction of "Cabal Hell", and might scare-off new haskellers. Would you consider recommending stack instead?

**Comment by tobiasgwaaler** [comment]
@k-bx yes, that's one of the things I would revise. I'd use `stack` instead :)

**Comment by snoyberg** [comment]
Such an addition would be great!

**Comment by tobiasgwaaler** [comment]
@snoyberg cool, I'll make a pull request as soon as I get the chance
